### ISSUE TITLE
Protelis-related IllegalArgumentException on Shadow JAR

### ISSUE THREAD

**Issue by NiccoMlt** [NiccoMlt/Protelis-Web#14]
When running code with `runShadow` Gradle task (provided by [Vert.x plugin for Gradle](https://github.com/jponge/vertx-gradle-plugin) and using [Gradle Shadow plugin](https://github.com/johnrengelman/shadow)), during simulation creation IllegalArgumentException is thrown:

> Exception in thread "DefaultDispatcher-worker-2" java.lang.IllegalArgumentException: Could not create the requested Protelis program: eval(env.get("_to_exec"))
> 	at it.unibo.alchemist.model.ProtelisIncarnation.createAction(ProtelisIncarnation.java:135)
> 	at it.unibo.alchemist.model.ProtelisIncarnation.createReaction(ProtelisIncarnation.java:208)
> 	at it.unibo.alchemist.loader.YamlLoader.lambda$getWith$22(YamlLoader.java:589)
> 	at it.unibo.alchemist.loader.YamlLoader$BuilderConfiguration.lambda$build$0(YamlLoader.java:864)
> 	at it.unibo.alchemist.loader.YamlLoader$BuilderConfiguration.ifMap(YamlLoader.java:872)
> 	at it.unibo.alchemist.loader.YamlLoader$BuilderConfiguration.build(YamlLoader.java:850)
> 	at it.unibo.alchemist.loader.YamlLoader$Builder.build(YamlLoader.java:830)
> 	at it.unibo.alchemist.loader.YamlLoader.getWith(YamlLoader.java:591)
> 	at it.unibo.alchemist.loader.YamlLoader.getDefault(YamlLoader.java:398)
> 	at it.unibo.protelis.web.execution.simulated.SimulatedProtelisEngine$setupSimulationAsync$1.invokeSuspend(SimulatedProtelisEngine.kt:66)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
> Caused by: java.util.MissingResourceException: The string resource '_UI_DiagnosticRoot_diagnostic' could not be located
> Caused by: java.util.MissingResourceException: The string resource '_UI_DiagnosticRoot_diagnostic' could not be located
> 
> 	at org.eclipse.emf.common.util.DelegatingResourceLocator.delegatedGetString(DelegatingResourceLocator.java:480)
> 	at org.eclipse.emf.common.util.DelegatingResourceLocator.getString(DelegatingResourceLocator.java:385)
> 	at org.eclipse.emf.common.util.DelegatingResourceLocator.getString(DelegatingResourceLocator.java:499)
> 	at org.eclipse.emf.common.util.DelegatingResourceLocator.getString(DelegatingResourceLocator.java:491)
> 	at org.eclipse.emf.ecore.util.Diagnostician.createDefaultDiagnostic(Diagnostician.java:88)
> 	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:107)
> 	at org.protelis.lang.ProtelisLoader.parse(ProtelisLoader.java:268)
> 	at org.protelis.lang.ProtelisLoader.parseAnonymousModule(ProtelisLoader.java:338)
> 	at org.protelis.lang.ProtelisLoader.lambda$parse$5(ProtelisLoader.java:317)
> 	at java.base/java.util.Optional.orElseGet(Optional.java:369)
> 	at org.protelis.lang.ProtelisLoader.parse(ProtelisLoader.java:317)
> 	at it.unibo.alchemist.model.implementations.actions.RunProtelisProgram.<init>(RunProtelisProgram.java:123)
> 	at it.unibo.alchemist.model.implementations.actions.RunProtelisProgram.<init>(RunProtelisProgram.java:96)
> 	at it.unibo.alchemist.model.ProtelisIncarnation.createAction(ProtelisIncarnation.java:133)
> 	... 15 more

This error does not happen when code is run with `vertxRun` task, so it's probably related to something missing in packetized shadow JAR.

**Comment by NiccoMlt** [comment]
I got this hint by email from professor:

> Sembra un problema con gli internals di Xtext.
> Forse manca qualche risorsa nel classpath
> 
> sì, parrebbe...
> https://stackoverflow.com/questions/38043360/error-when-validating-xtext-dsl-in-standalone-java-project

I also think these solutions could be helpful for my issue:

- > Create a `plugin.properties` file and jar it.
  > The content should contain this entry:
  > `_UI_DiagnosticRoot_diagnostic=_UI_DiagnosticRoot_diagnostic`
  
  from: https://www.eclipse.org/forums/index.php?t=msg&th=440750&goto=988308&#msg_988308
- > Found it:
  > 
  > Adding org.eclipse.emf.ecore/runtime/ecore.resources.jar to the classpath will work. See http://www.eclipse.org/emf/faq/faq.php#dnl20050114-120205 for more details.

  from: https://www.eclipse.org/forums/index.php?t=msg&th=130128&goto=402682&#msg_402682
- > I did the following:
  > 
  > 1. create a new xtext project.
  > 2. adapt workflow to generate java main for generator
  > 3. generate lang
  > 4. run generated java main once
  > 5. use the export as runnable jar file, tell it to create a ant file
  > 6. copy the ant file to the project
  > 7. adapted the ant file to include another file at the end
  >     ```xml
  >     <fileset dir="${dir.workspace}/org.xtext.example.mydsl2/">
  >         <include name="plugin.properties"/>
  >     </fileset>
  >     ```
  > 8. create org.xtext.example.mydsl2/plugin.properties as follows
  >     ```
  >     _UI_DiagnosticRoot_diagnostic=Dont Care`
  >    ``` 
  >    well i was too lazy to look up the real values and the other key value pairs
  > 
  > 9. rerun ant file
  > 10. have fun
  > 
  > if I'd be an ant wizard i would somehow adapt the `build.xml` to create a `plugin.properties` that contains all `plugin.properties` of the unpacked files merged
  > unfortunately i am not an ant wizard
  
  and
  
  > What I ended up doing was using the extract option and simply adding the `_UI_Diagnostic` line to the `plugin.properties` file, slightly annoying that simply trying to use a DSL in a standalone project is this troublesome, thank you for the assistance nonetheless.
  
  from: https://www.eclipse.org/forums/index.php?t=msg&th=1078740&goto=1738088&#msg_1738088

- > You need a plugin.properties file on you class path/your jar root
  > ```xml
  > <echo file="${binJarTemp}/plugin.properties">_UI_DiagnosticRoot_diagnostic=_UI_DiagnosticRoot_diagnostic</echo>
  > ```
  from: https://www.eclipse.org/forums/index.php?t=msg&th=487563&goto=1058824&#msg_1058824
